// Run report — printable HTML (FR-RPT-05; the browser's print dialog makes the PDF).
// Self-contained: no external stylesheet, font or image is referenced.
package reporting

import (
	"encoding/json"
	"fmt"
	"math"
	"strconv"
	"strings"

	"github.com/gin-gonic/gin"

	"traceo/internal/db"
	"traceo/internal/models"
)

// labels — the report vocabulary. The product is English-only, so there is one
// label set and the page is always rendered left-to-right.
var labels = map[string]string{
	"title": "Run Report", "project": "Project", "environment": "Environment",
	"run": "Run", "state": "State", "started": "Started", "finished": "Finished",
	"total": "Total", "passed": "Passed", "failed": "Failed", "errored": "Errored",
	"pass_rate": "Pass rate", "defects": "Defect reports", "results": "All results",
	"case": "Test case", "requirement": "Requirement", "steps": "Steps",
	"expected": "Expected", "actual": "Actual", "evidence": "Evidence",
	"request": "Request", "response": "Response", "assertion": "Assertion",
	"outcome": "Outcome", "duration": "Duration (ms)", "type": "Type",
	"priority": "Priority", "error": "Error",
	"no_failures": "No failures — every executed case passed.",
	"aborted":     "Run aborted", "generated_by": "Generated by Traceo",
}

const reportCSS = `
:root { --bg:#131217; --card:#1B1A21; --border:#312F3C; --amber:#FF8A22;
        --text:#EDEBF2; --muted:#9C98AB; --pass:#3DBB78; --fail:#E5534B; --err:#D9A03C; }
* { box-sizing: border-box; }
body { background: var(--bg); color: var(--text); margin: 0; padding: 32px;
       font: 14px/1.55 -apple-system, "Segoe UI", Tahoma, Arial, sans-serif; }
.mono { font-family: "SF Mono", ui-monospace, Menlo, Consolas, monospace; font-size: 12px; }
h1 { font-size: 24px; margin: 0 0 4px; }
h1 .accent { color: var(--amber); }
h2 { font-size: 17px; margin: 34px 0 12px; border-inline-start: 4px solid var(--amber);
     padding-inline-start: 10px; }
.meta { color: var(--muted); margin-bottom: 24px; }
.meta .mono { color: var(--text); }
.kpis { display: flex; flex-wrap: wrap; gap: 12px; margin: 20px 0 8px; }
.kpi { background: var(--card); border: 1px solid var(--border); border-radius: 10px;
       padding: 14px 20px; min-width: 128px; }
.kpi .num { font-size: 26px; font-weight: 700; }
.kpi .lbl { color: var(--muted); font-size: 12px; margin-top: 2px; }
.kpi.pass .num { color: var(--pass); } .kpi.fail .num { color: var(--fail); }
.kpi.err .num { color: var(--err); } .kpi.rate .num { color: var(--amber); }
.badge { display: inline-block; padding: 2px 10px; border-radius: 999px; font-size: 12px;
         font-weight: 600; border: 1px solid var(--border); }
.badge.passed { color: var(--pass); } .badge.failed { color: var(--fail); }
.badge.errored { color: var(--err); }
.card { background: var(--card); border: 1px solid var(--border); border-radius: 10px;
        padding: 18px 20px; margin-bottom: 16px; page-break-inside: avoid; }
.card h3 { margin: 0 0 8px; font-size: 15px; }
.reqs { color: var(--muted); font-size: 13px; margin-bottom: 10px; }
.reqs .rid { color: var(--amber); font-weight: 600; }
.kv { display: grid; grid-template-columns: 110px 1fr; gap: 4px 14px; margin: 10px 0; }
.kv .k { color: var(--muted); }
pre { background: var(--bg); border: 1px solid var(--border); border-radius: 8px;
      padding: 10px 12px; overflow-x: auto; white-space: pre-wrap; word-break: break-word;
      font-family: "SF Mono", ui-monospace, Menlo, Consolas, monospace; font-size: 12px;
      margin: 6px 0 12px; direction: ltr; text-align: left; }
.step { border-top: 1px dashed var(--border); padding-top: 10px; margin-top: 10px; }
.step .line { font-weight: 600; }
table { border-collapse: collapse; width: 100%; background: var(--card);
        border: 1px solid var(--border); border-radius: 10px; overflow: hidden; }
th { background: var(--amber); color: #131217; text-align: start; font-size: 12px;
     padding: 9px 12px; }
td { border-top: 1px solid var(--border); padding: 8px 12px; font-size: 13px;
     vertical-align: top; }
.footer { color: var(--muted); font-size: 12px; margin-top: 36px; }
@media print {
  :root { --bg:#FFFFFF; --card:#FFFFFF; --border:#D8D5E0; --text:#1B1A21;
          --muted:#5E5A6E; }
  body { padding: 0; }
  .kpi, .card, table { box-shadow: none; }
  th { color: #FFFFFF; background: #FF8A22; -webkit-print-color-adjust: exact;
       print-color-adjust: exact; }
}
`

// ---------------------------------------------------------------------------
// Rendering primitives (ports of html.escape / json.dumps / str())
// ---------------------------------------------------------------------------

var escaper = strings.NewReplacer(
	"&", "&amp;", "<", "&lt;", ">", "&gt;", `"`, "&quot;", "'", "&#x27;")

// pyStr mirrors Python's str() for the values that reach the template: JSON
// numbers arrive as float64 but were written as ints, so render them as ints.
func pyStr(v any) string {
	switch t := v.(type) {
	case nil:
		return ""
	case string:
		return t
	case bool:
		if t {
			return "True"
		}
		return "False"
	case float64:
		if t == math.Trunc(t) && math.Abs(t) < 1e15 {
			return strconv.FormatInt(int64(t), 10)
		}
		return strconv.FormatFloat(t, 'g', -1, 64)
	case float32:
		return pyStr(float64(t))
	case int:
		return strconv.Itoa(t)
	case int64:
		return strconv.FormatInt(t, 10)
	case json.Number:
		return t.String()
	}
	return fmt.Sprint(v)
}

// esc — html.escape(str(v), quote=True).
func esc(v any) string { return escaper.Replace(pyStr(v)) }

// jsonIndentBytes — json.dumps(v, ensure_ascii=False, indent=2, default=str).
func jsonIndentBytes(v any) string {
	var b strings.Builder
	enc := json.NewEncoder(&b)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(v); err != nil {
		return pyStr(v)
	}
	return strings.TrimSuffix(b.String(), "\n")
}

func jsonish(v any) string {
	if v == nil {
		return ""
	}
	if s, ok := v.(string); ok {
		return s
	}
	return jsonIndentBytes(v)
}

// orderedJSON renders an object with the keys in the given order (Python dicts
// preserve insertion order; Go maps marshal alphabetically).
func orderedJSON(keys []string, vals []any) string {
	parts := make([]string, 0, len(keys))
	for i, k := range keys {
		kb, _ := json.Marshal(k)
		body := strings.ReplaceAll(jsonIndentBytes(vals[i]), "\n", "\n  ")
		parts = append(parts, "  "+string(kb)+": "+body)
	}
	return "{\n" + strings.Join(parts, ",\n") + "\n}"
}

// clip — display cap counted in characters, as Python's len() on a str.
func clip(text string) string {
	r := []rune(text)
	if len(r) > evidenceHTMLMax {
		return string(r[:evidenceHTMLMax]) + "…[truncated]"
	}
	return text
}

func label(l map[string]string, key string) string {
	if v, ok := l[key]; ok {
		return v
	}
	return key
}

// ---------------------------------------------------------------------------
// Defect card
// ---------------------------------------------------------------------------

func defectCard(e *reportEntry, l map[string]string) string {
	fr := e.FailureReason
	if fr == nil {
		fr = models.JSONMap{}
	}
	var reqs strings.Builder
	for _, r := range e.Requirements {
		reqs.WriteString(`<div><span class="rid mono">` + esc(r.label()) + `</span> ` +
			esc(r.Description) + `</div>`)
	}
	outcomeLbl := label(l, e.Outcome)

	diag := ""
	if fr["assertion"] != nil {
		diag = `<div class="kv">` +
			`<div class="k">` + l["assertion"] + `</div>` +
			`<div class="mono">` + esc(jsonish(fr["assertion"])) + `</div>` +
			`<div class="k">` + l["expected"] + `</div>` +
			`<div class="mono">` + esc(jsonish(fr["expected"])) + `</div>` +
			`<div class="k">` + l["actual"] + `</div>` +
			`<div class="mono">` + esc(jsonish(fr["actual"])) + `</div>` +
			`</div>`
	} else if truthy(fr["error"]) {
		diag = `<div class="kv"><div class="k">` + l["error"] + `</div>` +
			`<div class="mono">` + esc(fr["error"]) + `</div></div>`
	}

	var steps strings.Builder
	for i, raw := range e.Evidence {
		ev := asMap(raw)
		if ev == nil {
			ev = map[string]any{}
		}
		reqEv := asMap(ev["request"])
		if reqEv == nil {
			reqEv = map[string]any{}
		}
		elapsed := any(0)
		if v, ok := ev["elapsed_ms"]; ok {
			elapsed = v
		}
		steps.WriteString(`<div class="step"><div class="line mono">` +
			fmt.Sprintf("%d. ", i+1) + esc(reqEv["method"]) + " " + esc(reqEv["url"]) +
			" — " + pyStr(elapsed) + "ms</div>")

		// {k: request[k] for k in ("headers", "body") if request[k]} — insertion order.
		var keys []string
		var vals []any
		for _, k := range []string{"headers", "body"} {
			if truthy(reqEv[k]) {
				keys = append(keys, k)
				vals = append(vals, reqEv[k])
			}
		}
		if len(keys) > 0 {
			steps.WriteString(`<div class="k">` + l["request"] + `</div>` +
				`<pre>` + esc(clip(orderedJSON(keys, vals))) + `</pre>`)
		}
		if respEv, present := ev["response"]; present && respEv != nil {
			rm := asMap(respEv)
			if rm == nil {
				rm = map[string]any{}
			}
			steps.WriteString(`<div class="k">` + l["response"] + ` — HTTP ` +
				esc(rm["status"]) + `</div>` +
				`<pre>` + esc(clip(jsonish(rm["body"]))) + `</pre>`)
		} else if truthy(ev["error"]) {
			steps.WriteString(`<div class="k">` + l["error"] + `</div>` +
				`<pre>` + esc(clip(pyStr(ev["error"]))) + `</pre>`)
		}
		steps.WriteString(`</div>`)
	}
	stepsHTML := steps.String()
	if stepsHTML == "" {
		stepsHTML = "<div class=step>—</div>"
	}
	reqsHTML := reqs.String()
	if reqsHTML == "" {
		reqsHTML = " —"
	}

	return `<div class="card">` +
		`<h3>` + esc(e.TC.Title) + ` ` +
		`<span class="badge ` + e.Outcome + `">` + esc(outcomeLbl) + `</span></h3>` +
		`<div class="reqs"><strong>` + l["requirement"] + `:</strong>` + reqsHTML + `</div>` +
		diag +
		`<div class="k" style="color:var(--muted)">` +
		l["steps"] + ` / ` + l["evidence"] + `</div>` +
		stepsHTML +
		`</div>`
}

// ---------------------------------------------------------------------------
// Handler
// ---------------------------------------------------------------------------

const pageTemplate = `<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>%s — %s</title>
<style>%s</style>
</head>
<body>
<h1><span class="accent">Traceo</span> — %s</h1>
<div class="meta">
  %s: <strong>%s</strong> ·
  %s: <strong>%s</strong> ·
  %s: <span class="mono">#%d</span>
  <span class="mono" style="color:var(--muted)">%s</span><br>
  %s: %s ·
  %s: <span class="mono">%s</span> ·
  %s: <span class="mono">%s</span>
</div>
%s
<div class="kpis">
  <div class="kpi"><div class="num">%d</div><div class="lbl">%s</div></div>
  <div class="kpi pass"><div class="num">%d</div><div class="lbl">%s</div></div>
  <div class="kpi fail"><div class="num">%d</div><div class="lbl">%s</div></div>
  <div class="kpi err"><div class="num">%d</div><div class="lbl">%s</div></div>
  <div class="kpi rate"><div class="num">%s</div><div class="lbl">%s</div></div>
</div>
<h2>%s</h2>
%s
<h2>%s</h2>
<table>
<thead><tr><th>%s</th><th>%s</th><th>%s</th>
<th>%s</th><th>%s</th><th>%s</th></tr></thead>
<tbody>%s</tbody>
</table>
<div class="footer">%s · %s</div>
</body>
</html>`

func runReportHTML(c *gin.Context) {
	run, ok := getRunByID(c, c.Param("id"))
	if !ok {
		return
	}
	var project models.Project
	hasProject := db.DB.First(&project, "id = ?", run.ProjectID).Error == nil
	var env models.Environment
	hasEnv := db.DB.First(&env, "id = ?", run.EnvironmentID).Error == nil

	entries := reportEntries(run)
	counts := countsOf(run, entries)
	displayID := runDisplayID(run)

	l := labels

	total := numInt(counts["total"])
	passed := numInt(counts["passed"])
	rate := "—"
	if total != 0 {
		rate = strconv.FormatFloat(float64(passed)/float64(total)*100, 'f', 1, 64) + "%"
	}

	var defects strings.Builder
	for _, e := range entries {
		if e.Outcome == "failed" || e.Outcome == "errored" {
			defects.WriteString(defectCard(e, l))
		}
	}
	defectsHTML := defects.String()
	if defectsHTML == "" {
		defectsHTML = `<div class="card">` + l["no_failures"] + `</div>`
	}

	var rows strings.Builder
	for _, e := range entries {
		var reqCells strings.Builder
		for _, r := range e.Requirements {
			reqCells.WriteString(`<div class=mono>` + esc(r.label()) + `</div>`)
		}
		reqCell := reqCells.String()
		if reqCell == "" {
			reqCell = "—"
		}
		rows.WriteString(`<tr><td>` + esc(e.TC.Title) +
			`<div class="mono" style="color:var(--muted)">` + esc(e.TC.ID) + `</div></td>` +
			`<td>` + esc(e.TC.Type) + `</td>` +
			`<td>` + esc(e.TC.Priority) + `</td>` +
			`<td><span class="badge ` + e.Outcome + `">` + esc(label(l, e.Outcome)) + `</span></td>` +
			`<td class="mono">` + strconv.Itoa(e.DurationMs) + `</td>` +
			`<td>` + reqCell + `</td>` +
			`</tr>`)
	}
	resultRows := rows.String()
	if resultRows == "" {
		resultRows = `<tr><td colspan="6">—</td></tr>`
	}

	abortHTML := ""
	if run.State == "aborted" {
		abortHTML = `<div class="card"><h3>` + l["aborted"] + `</h3>` +
			`<pre>` + esc(run.AbortReason) + `</pre></div>`
	}

	titleName := run.ProjectID
	metaName := "?"
	if hasProject {
		titleName = project.Name
		metaName = project.Name
	}
	envName := "?"
	if hasEnv {
		envName = env.Name
	}
	started := isoPtrStr(run.StartedAt)
	if started == "" {
		started = "—"
	}
	finished := isoPtrStr(run.FinishedAt)
	if finished == "" {
		finished = "—"
	}

	page := fmt.Sprintf(pageTemplate,
		l["title"], esc(titleName),
		reportCSS,
		l["title"],
		l["project"], esc(metaName),
		l["environment"], esc(envName),
		l["run"], displayID,
		esc(run.ID),
		l["state"], esc(run.State),
		l["started"], esc(started),
		l["finished"], esc(finished),
		abortHTML,
		total, l["total"],
		passed, l["passed"],
		numInt(counts["failed"]), l["failed"],
		numInt(counts["errored"]), l["errored"],
		rate, l["pass_rate"],
		l["defects"], defectsHTML,
		l["results"],
		l["case"], l["type"], l["priority"],
		l["outcome"], l["duration"], l["requirement"],
		resultRows,
		l["generated_by"], esc(iso(run.CreatedAt)),
	)
	c.Data(200, "text/html; charset=utf-8", []byte(page))
}
