// Package reference — GET /reference/features: static feature catalog (v2 addendum),
// a verbatim port of backend/app/modules/reference.py. 37 features across 8
// capability groups; `status` reflects THIS codebase honestly: built = exercised by
// the running backend today, planned = referenced by the design but not implemented.
//
// The catalog is English-only (product pivot): every entry carries name_en and
// description_en, the keys the UI reads.
package reference

import (
	"github.com/gin-gonic/gin"

	"traceo/internal/httpx"
)

func f(id, group, nameEn, priority, status, descriptionEn string) gin.H {
	return gin.H{"id": id, "group": group, "name_en": nameEn,
		"priority": priority, "status": status, "description_en": descriptionEn}
}

var groups = []gin.H{
	{"key": "parser", "name_en": "Layer 1 — Parser"},
	{"key": "discovery", "name_en": "Layer 2 — Discovery"},
	{"key": "generator", "name_en": "Layer 3 — Generator"},
	{"key": "execution", "name_en": "Layer 4 — Execution"},
	{"key": "reporting", "name_en": "Layer 5 — Reporting"},
	{"key": "automation", "name_en": "Automation"},
	{"key": "integrations", "name_en": "Integrations"},
	{"key": "platform", "name_en": "Platform"},
}

var features = []gin.H{
	f("FR-010", "parser", "Requirements ingestion",
		"P0", "built",
		"Upload a PDF, DOCX, Markdown or plain-text requirements document; Traceo extracts every requirement with an ID, a description, a type and a priority, all correctable before generation."),
	f("FR-011", "parser", "Confluence import",
		"P1", "planned",
		"Pull requirement pages from a Confluence space instead of uploading a file, detecting changed pages on re-import."),
	f("FR-012", "parser", "Unicode-safe requirement parsing",
		"P0", "built",
		"Parse RFP and BRD documents that carry non-ASCII text with the same accuracy as plain ASCII, including digit normalisation and mixed-script segments."),
	f("FR-013", "parser", "Acceptance-criteria extraction",
		"P0", "built",
		"Break every requirement into atomic, testable acceptance criteria that test cases are built from and measured against in the matrix."),
	f("FR-014", "parser", "Source traceback",
		"P1", "built",
		"Every requirement keeps a link to its source document and source text, and the trace stays valid after re-parsing an updated version of that document."),
	f("FR-020", "discovery", "OpenAPI discovery",
		"P0", "built",
		"Read endpoints, parameters and schemas straight from an OpenAPI 3.x or Swagger 2.0 specification, by upload or URL, resolving internal references safely."),
	f("FR-021", "discovery", "Traffic-capture discovery",
		"P0", "planned",
		"A headless browser drives the application and builds the endpoint map from the observed network traffic, redacting credentials before storage."),
	f("FR-022", "discovery", "DOM crawl",
		"P1", "planned",
		"Collect forms, fields and client-side validation rules from the rendered DOM to feed boundary and equivalence inputs."),
	f("FR-023", "discovery", "Postman import",
		"P2", "planned",
		"Import an existing Postman v2.1 collection and treat it as a discovered surface, flagged by its source in the coverage map."),
	f("FR-024", "discovery", "Endpoint coverage map",
		"P1", "built",
		"Every discovered endpoint shows how many tests hit it, the share of its parameters covered and its latest execution outcome."),
	f("FR-030", "generator", "Boundary value analysis",
		"P0", "built",
		"Generate cases for the minimum, the maximum and just beyond every edge of each numerically or length-constrained field, derived from the specification schema."),
	f("FR-031", "generator", "Equivalence partitioning",
		"P0", "built",
		"One representative case per valid and invalid class, derived from the declared enums, formats and rules."),
	f("FR-032", "generator", "Decision tables",
		"P1", "built",
		"Enumerate rule and condition combinations for business-rule requirements when two or more constraints interact (exhaustive depth)."),
	f("FR-033", "generator", "Negative & auth cases",
		"P0", "built",
		"Missing parameter, wrong type, malformed body, an unauthenticated request against a secured operation, and injection-shaped strings tested safely."),
	f("FR-034", "generator", "Unicode / localisation checks",
		"P1", "built",
		"Non-ASCII payloads — accented Latin, CJK, emoji, zero-width characters and NFC-vs-NFD pairs — round-tripped through free-text fields, generated by default in every generation."),
	f("FR-035", "generator", "Grounded generation",
		"P0", "built",
		"Generation is confined to the discovered endpoints; a strict grounding gate checks every step and drops any case that references an endpoint or a field that does not exist — it is never repaired."),
	f("FR-036", "generator", "Test case library",
		"P1", "built",
		"Every generated case is browsable, filterable and editable; manual edits are flagged and manual cases count in the matrix exactly like generated ones."),
	f("FR-040", "execution", "HTTP execution engine",
		"P0", "built",
		"Execute the approved cases against the project environment with configurable concurrency, a single authentication per run, and mid-run cancellation that keeps the partial results."),
	f("FR-041", "execution", "Schema assertions",
		"P0", "built",
		"Validate the response body against the response schema declared in the specification; a violation fails the case even when the status code is correct."),
	f("FR-042", "execution", "Business-rule assertions",
		"P0", "built",
		"Assertions derived from the acceptance criteria, not from status codes alone, with the failure message showing expected and actual side by side."),
	f("FR-043", "execution", "Test data lifecycle",
		"P1", "planned",
		"Provision test data before the suite and tear it down afterwards on every run, reporting any data that could not be removed."),
	f("FR-044", "execution", "Performance capture",
		"P2", "built",
		"Record the response time of every case and report p50/p95/max per endpoint, with a response_time_ms assertion able to fail a case that exceeds its budget."),
	f("FR-050", "reporting", "Traceability matrix",
		"P0", "built",
		"Requirement to test cases to verdict, always current after every run and every requirement change, and exportable as XLSX."),
	f("FR-051", "reporting", "Coverage gap detection",
		"P0", "built",
		"Every requirement without an approved case appears as a gap with a clear reason and a suggested next action."),
	f("FR-052", "reporting", "Reproducible bug reports",
		"P0", "built",
		"Numbered steps, the redacted request and response log, and the failing assertion with expected and actual, with a severity derived from the requirement priority and the failure class."),
	f("FR-053", "reporting", "Run comparison",
		"P1", "built",
		"Compare any two runs of the same project: the new failures, the fixes and the coverage delta."),
	f("FR-054", "reporting", "Coverage trend",
		"P1", "built",
		"Plot the last 14 completed runs with their coverage value and their outcomes on the project dashboard."),
	f("FR-060", "automation", "Scheduled runs",
		"P1", "built",
		"A schedule per project and environment with a minimum interval of 15 minutes; a scheduler thread fires the same path as a manual run and the run appears in history with source `schedule`."),
	f("FR-061", "automation", "CI/CD gate",
		"P0", "built",
		"A gate endpoint on public API keys: a minimum coverage, a maximum number of critical defects and failures; `?exit=1` returns 412 to fail the pipeline and names the offending requirements."),
	f("FR-062", "automation", "Regression watch",
		"P1", "built",
		"Highlight on the project dashboard every requirement that used to pass and has started failing, with its state and its severity."),
	f("FR-070", "integrations", "Jira / Xray export",
		"P0", "built",
		"Export run results in the Xray import format (xray.json) and the failures as a Jira-ready CSV with the steps, the severity and the requirement IDs."),
	f("FR-071", "integrations", "PDF / XLSX report export",
		"P1", "built",
		"The traceability matrix as an XLSX workbook, and a printable HTML run report that doubles as the PDF deliverable through the browser's print dialog."),
	f("FR-072", "integrations", "Slack notifications",
		"P2", "built",
		"Webhooks on run completion signed with HMAC, plus a special case for Slack Incoming Webhook URLs that posts a short summary with the result counts."),
	f("FR-080", "platform", "Role-based access",
		"P1", "built",
		"Four roles (admin, QA lead, QA engineer, viewer) enforced server-side through a per-endpoint permission matrix."),
	// planned, not built: the stack runs offline (local SQLite, offline mock LLM
	// provider), but there is no deployment artefact yet — no container image, no
	// compose file, no upgrade path. Claiming "built" here would misrepresent the
	// product in the UI, since this catalog is shown to customers.
	f("FR-081", "platform", "On-premise deployment",
		"P0", "planned",
		"The components run without internet access (local SQLite and a mock LLM provider), but there is no deployment package yet: no container image, no compose file, no upgrade path."),
	f("FR-082", "platform", "Audit log",
		"P1", "built",
		"Every configuration change and every run is written to an append-only, immutable log, with a full organisation data export (PDPL)."),
	f("FR-083", "platform", "Secrets vault",
		"P0", "built",
		"Credentials for the system under test are encrypted at rest and are never written to logs, reports or captured evidence."),
}

func init() {
	if len(features) != 37 {
		panic("feature catalog must stay at 37 entries")
	}
}

func Register(r *gin.RouterGroup) {
	r.GET("/reference/features", httpx.Auth(), httpx.Require("view"), listFeatures)
}

func listFeatures(c *gin.Context) {
	built, planned := 0, 0
	for _, ft := range features {
		if ft["status"] == "built" {
			built++
		} else {
			planned++
		}
	}
	c.JSON(200, gin.H{"groups": groups, "features": features,
		"counts": gin.H{"total": len(features), "built": built, "planned": planned}})
}
