// classify.go — the pure-function classifier for LEGACY cases.
//
// Cases created by the insight engine carry edge_category directly. Everything
// that existed before it (generated by the ISTQB techniques, or hand-authored)
// has a NULL edge_category, yet some of those cases already cover an insight
// category — counting them as gaps would be a lie. Classify() answers "which
// category does this pre-existing case already cover?" from its steps and title.
// It touches no database and no clock: same input, same output, always.
//
// PARITY: this is a line-for-line mirror of classify_case() in the Python engine
// (backend/app/modules/insight.py). The two backends must return the SAME
// covered_count for the same project, so the rule order, the character classes,
// the pagination names and the keyword lists below are all deliberately
// identical. Change one side and you must change the other.
//
// RULES, in strict priority order (first match wins — the order matters because
// one case can carry several signals, e.g. a NUL byte inside a CJK string):
//
//  0. an explicit, legal edge_category always wins.
//  1. REQUEST-VALUE signals (strongest: they describe what the case actually
//     sends, not what someone called it):
//     1a. a C0/C1 control character or NUL in any string value -> control_chars
//     1b. any non-ASCII character in a request value (CJK, accented Latin,
//     emoji, zero-width/bidi marks, NFD combining marks)      -> exotic_input
//     NOTE: only *request values* are inspected, never the title — a title is
//     prose and would false-positive on any typographic character.
//     1c. >= 2 steps repeating the SAME mutating (method, path)  -> idempotency
//     1d. a string value >= 1000 chars, or a pagination-named parameter with an
//     extreme value                                   -> resource_exhaustion
//     1e. an assertion that tolerates a 5xx                -> downstream_failure
//     1f. an assertion expecting 401/403                      -> permission_edge
//     1g. a date/date-time-shaped value carrying a timezone offset, a leap day
//     or a 12-31/01-01 rollover                                -> timing_dst
//     1h. >= 2 steps whose mutating (method, path) pairs differ -> state_corruption
//  2. TITLE keywords, for hand-written cases that state the intent without a
//     machine-readable signal.
//  3. otherwise "" — the case belongs to no edge family.
//
// DELIBERATELY NOT A RULE: technique "bva" / type "boundary" do NOT imply
// boundary_surprise. Taxonomy item A defines that category as the off-by-one and
// limit edges *beyond plain BVA*; plain BVA walks min, min+1, max-1, max — all
// INSIDE the declared range — and never sends the min-1/max+1 values the builder
// emits. Crediting every BVA case would report "covered" on exactly the projects
// whose just-outside edges are untested, which is the blind spot this engine
// exists to expose. Only the explicit just-outside vocabulary counts.
package insight

import (
	"regexp"
	"strings"

	"traceo/internal/models"
)

// titleHints — evaluated in slice order, first hit wins. Mirrors _TITLE_HINTS.
var titleHints = []struct {
	category string
	needles  []string
}{
	{"control_chars", []string{"null byte", "nul byte", "control char"}},
	{"idempotency", []string{"idempot", "duplicate submit", "double submit", "replay"}},
	{"permission_edge", []string{"unauthenticated", "unauthorised", "unauthorized",
		"forbidden", "permission", "privilege", "lower-privileged"}},
	{"resource_exhaustion", []string{"oversized", "too large", "payload limit",
		"pagination", "exhaustion"}},
	{"timing_dst", []string{"timezone", "time zone", "dst", "daylight", "rollover",
		"leap day"}},
	{"state_corruption", []string{"out of order", "out-of-order", "illegal transition",
		"after delete", "before create"}},
	{"downstream_failure", []string{"downstream", "upstream", "dependency failure", "5xx"}},
	{"exotic_input", []string{"non-ascii", "emoji", "unicode", "normalisation",
		"normalization", "localisation", "localization", "zero-width"}},
	// Just-outside vocabulary ONLY. A bare "boundary" is the plain-BVA word.
	{"boundary_surprise", []string{"off-by-one", "off by one", "just outside",
		"just-outside", "beyond the limit", "past the declared", "minimum-1", "maximum+1",
		"minlength-1", "maxlength+1"}},
}

// paginationParamNames — the same closed set the Python engine uses.
var paginationParamNames = map[string]bool{
	"limit": true, "page": true, "page_size": true, "pagesize": true, "per_page": true,
	"perpage": true, "offset": true, "size": true, "count": true, "top": true,
	"skip": true, "take": true, "max_results": true, "maxresults": true, "rows": true,
}

var (
	dateRe     = regexp.MustCompile(`\d{4}-\d{2}-\d{2}`)
	tzOffsetRe = regexp.MustCompile(`\d{2}:\d{2}(?:Z|[+-]\d{2}:?\d{2})`)
)

var mutatingClassify = map[string]bool{
	"POST": true, "PUT": true, "PATCH": true, "DELETE": true,
}

// Classify returns the insight category a pre-existing case already covers, or
// "" when it covers none. edgeCategory (when set and legal) always wins: the
// engine's own cases are never re-classified.
func Classify(tc *models.TestCase, steps []models.TestStep) string {
	if tc.EdgeCategory != nil && IsCategory(*tc.EdgeCategory) {
		return *tc.EdgeCategory
	}

	var hasControl, hasExotic, hasLongString, hasExtremePage, hasTiming bool
	codes := map[int]bool{}
	var mutatingKeys []string

	for i := range steps {
		m := strings.ToUpper(steps[i].Method)
		if mutatingClassify[m] {
			mutatingKeys = append(mutatingKeys, m+" "+steps[i].Path)
		}
		request := map[string]any(steps[i].Request)
		for _, code := range assertCodes(steps[i].Assertions) {
			codes[code] = true
		}
		for _, text := range requestStrings(request) {
			if hasControlChar(text) {
				hasControl = true
			}
			if isExoticText(text) {
				hasExotic = true
			}
			if len([]rune(text)) >= 1000 {
				hasLongString = true
			}
			if dateRe.MatchString(text) && (tzOffsetRe.MatchString(text) ||
				strings.Contains(text, "-02-29") || strings.Contains(text, "-12-31") ||
				strings.Contains(text, "-01-01")) {
				hasTiming = true
			}
		}
		for key, value := range requestScalars(request) {
			if !paginationParamNames[strings.ToLower(key)] {
				continue
			}
			if n, ok := asInt(value); ok && (n < 0 || n >= 100000) {
				hasExtremePage = true
			}
		}
	}

	// 1. request-value signals
	if hasControl {
		return "control_chars"
	}
	if hasExotic {
		return "exotic_input"
	}
	if len(mutatingKeys) >= 2 && distinctCount(mutatingKeys) == 1 {
		return "idempotency"
	}
	if hasLongString || hasExtremePage {
		return "resource_exhaustion"
	}
	for c := range codes {
		if c >= 500 && c < 600 {
			return "downstream_failure"
		}
	}
	if codes[401] || codes[403] {
		return "permission_edge"
	}
	if hasTiming {
		return "timing_dst"
	}
	if len(mutatingKeys) >= 2 && distinctCount(mutatingKeys) > 1 {
		return "state_corruption"
	}

	// 2. title keywords
	title := strings.ToLower(tc.Title)
	for _, rule := range titleHints {
		for _, needle := range rule.needles {
			if strings.Contains(title, needle) {
				return rule.category
			}
		}
	}

	// 3. no technique/type fallback — see the rule table above.
	return ""
}

func distinctCount(keys []string) int {
	seen := map[string]bool{}
	for _, k := range keys {
		seen[k] = true
	}
	return len(seen)
}

// requestStrings — every string value a step sends (params, headers, body, and a
// string raw_body). Mirrors _iter_request_strings.
func requestStrings(request map[string]any) []string {
	var out []string
	var walk func(v any)
	walk = func(v any) {
		switch t := v.(type) {
		case string:
			out = append(out, t)
		case map[string]any:
			for _, k := range sortedKeys(t) {
				walk(t[k])
			}
		case models.JSONMap:
			walk(map[string]any(t))
		case []any:
			for _, item := range t {
				walk(item)
			}
		case models.JSONList:
			walk([]any(t))
		}
	}
	for _, section := range []string{"params", "headers", "body"} {
		walk(request[section])
	}
	if raw, ok := request["raw_body"].(string); ok {
		out = append(out, raw)
	}
	return out
}

// requestScalars — (key, value) for every top-level scalar in params and body,
// used for the pagination probe. Mirrors _iter_request_values.
func requestScalars(request map[string]any) map[string]any {
	out := map[string]any{}
	for _, section := range []string{"params", "body"} {
		if sub := asMap(request[section]); sub != nil {
			for k, v := range sub {
				out[k] = v
			}
		}
	}
	return out
}

// assertCodes — every integer status code an assertion names, expected and
// expected_any alike. Mirrors _assert_codes.
func assertCodes(assertions models.JSONList) []int {
	var out []int
	for _, av := range assertions {
		a := asMap(av)
		if a == nil || str(a["type"]) != "status_code" {
			continue
		}
		if n, ok := asInt(a["expected"]); ok {
			out = append(out, n)
		}
		for _, xv := range asList(a["expected_any"]) {
			if n, ok := asInt(xv); ok {
				out = append(out, n)
			}
		}
	}
	return out
}

// hasControlChar — C0 and C1 control characters plus DEL, excluding tab, LF and
// CR. Mirrors the _CONTROL_RE character class exactly.
func hasControlChar(s string) bool {
	for _, r := range s {
		if (r >= 0x00 && r <= 0x08) || r == 0x0b || r == 0x0c ||
			(r >= 0x0e && r <= 0x1f) || (r >= 0x7f && r <= 0x9f) {
			return true
		}
	}
	return false
}

// isExoticText — ANY non-ASCII character in a request value. Mirrors
// _is_exotic_text.
//
// The evidence is deliberately general: the exotic_input probes send accented
// Latin, CJK, emoji, zero-width/bidi marks and NFD combining marks, and every
// one of those lives above U+007F. A legacy case that already round-trips any
// non-ASCII text through a field therefore covers what this category would
// otherwise suggest. Control characters are caught by rule 1a first, which runs
// before this one, so the C1 range never lands here.
func isExoticText(s string) bool {
	for _, r := range s {
		if r > 0x7f {
			return true
		}
	}
	return false
}
