"""baseline schema (v1 + v2 addendum)

Revision ID: 7adc805d4ac4
Revises: 
Create Date: 2026-07-30 02:35:41.115460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7adc805d4ac4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('prefix', sa.String(length=12), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_organisation_id'), ['organisation_id'], unique=False)

    op.create_table('audit_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('object_type', sa.String(length=40), nullable=False),
    sa.Column('object_id', sa.String(length=36), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_entries_organisation_id'), ['organisation_id'], unique=False)

    op.create_table('projects',
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_organisation_id'), ['organisation_id'], unique=False)

    op.create_table('users',
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_organisation_id'), ['organisation_id'], unique=False)

    op.create_table('api_specs',
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_specs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_specs_organisation_id'), ['organisation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_specs_project_id'), ['project_id'], unique=False)

    op.create_table('environments',
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('auth_type', sa.String(length=20), nullable=False),
    sa.Column('auth_config_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('tls_strict', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_environments_organisation_id'), ['organisation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_environments_project_id'), ['project_id'], unique=False)

    op.create_table('source_documents',
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parse_status', sa.String(length=20), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_documents_organisation_id'), ['organisation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_documents_project_id'), ['project_id'], unique=False)

    op.create_table('test_cases',
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('preconditions', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('generated', sa.Boolean(), nullable=False),
    sa.Column('user_modified', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('technique', sa.String(length=30), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_cases_organisation_id'), ['organisation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_cases_project_id'), ['project_id'], unique=False)

    op.create_table('webhooks',
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('secret', sa.String(length=200), nullable=True),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_status', sa.Integer(), nullable=True),
    sa.Column('last_fired_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhooks_organisation_id'), ['organisation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhooks_project_id'), ['project_id'], unique=False)

    op.create_table('endpoints',
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('api_spec_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('operation_id', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('request_schema', sa.JSON(), nullable=True),
    sa.Column('response_schemas', sa.JSON(), nullable=False),
    sa.Column('security', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_spec_id'], ['api_specs.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_endpoints_api_spec_id'), ['api_spec_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_endpoints_organisation_id'), ['organisation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_endpoints_project_id'), ['project_id'], unique=False)

    op.create_table('requirements',
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_location', sa.JSON(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirements_organisation_id'), ['organisation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_project_id'), ['project_id'], unique=False)

    op.create_table('runs',
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('counts', sa.JSON(), nullable=False),
    sa.Column('initiated_by', sa.String(length=36), nullable=False),
    sa.Column('abort_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_organisation_id'), ['organisation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_project_id'), ['project_id'], unique=False)

    op.create_table('schedules',
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_organisation_id'), ['organisation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_project_id'), ['project_id'], unique=False)

    op.create_table('requirement_test_cases',
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('test_case_id', sa.String(length=36), nullable=False),
    sa.Column('link_source', sa.String(length=20), nullable=False),
    sa.Column('requirement_version_at_link', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('requirement_id', 'test_case_id')
    )
    op.create_table('test_results',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('test_case_id', sa.String(length=36), nullable=False),
    sa.Column('test_case_version', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_results_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_results_test_case_id'), ['test_case_id'], unique=False)

    op.create_table('test_steps',
    sa.Column('test_case_id', sa.String(length=36), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.String(length=36), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('request', sa.JSON(), nullable=False),
    sa.Column('assertions', sa.JSON(), nullable=False),
    sa.Column('extractions', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_steps_test_case_id'), ['test_case_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_steps_test_case_id'))

    op.drop_table('test_steps')
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_results_test_case_id'))
        batch_op.drop_index(batch_op.f('ix_test_results_run_id'))

    op.drop_table('test_results')
    op.drop_table('requirement_test_cases')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_project_id'))
        batch_op.drop_index(batch_op.f('ix_schedules_organisation_id'))

    op.drop_table('schedules')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_project_id'))
        batch_op.drop_index(batch_op.f('ix_runs_organisation_id'))

    op.drop_table('runs')
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirements_project_id'))
        batch_op.drop_index(batch_op.f('ix_requirements_organisation_id'))

    op.drop_table('requirements')
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_endpoints_project_id'))
        batch_op.drop_index(batch_op.f('ix_endpoints_organisation_id'))
        batch_op.drop_index(batch_op.f('ix_endpoints_api_spec_id'))

    op.drop_table('endpoints')
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhooks_project_id'))
        batch_op.drop_index(batch_op.f('ix_webhooks_organisation_id'))

    op.drop_table('webhooks')
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_cases_project_id'))
        batch_op.drop_index(batch_op.f('ix_test_cases_organisation_id'))

    op.drop_table('test_cases')
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_documents_project_id'))
        batch_op.drop_index(batch_op.f('ix_source_documents_organisation_id'))

    op.drop_table('source_documents')
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environments_project_id'))
        batch_op.drop_index(batch_op.f('ix_environments_organisation_id'))

    op.drop_table('environments')
    with op.batch_alter_table('api_specs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_specs_project_id'))
        batch_op.drop_index(batch_op.f('ix_api_specs_organisation_id'))

    op.drop_table('api_specs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organisation_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_organisation_id'))

    op.drop_table('projects')
    with op.batch_alter_table('audit_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_entries_organisation_id'))

    op.drop_table('audit_entries')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_organisation_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))

    op.drop_table('api_keys')
    op.drop_table('organisations')
    # ### end Alembic commands ###
